### ISSUE TITLE
Total Amount Needed per Science Pack

### ISSUE THREAD

**Issue by Demariosphere** [raiguard/UltimateResearchQueue#12] opened 2023-10-15 03:34 UTC
I don't know if this is possible or not, but can you show total amount of science packs needed from the researched held without counting it manually?
For instance: I do 3 research, so total I need is 3500 per science pack.

**Comment by raiguard** [comment] 2023-10-15 16:51
Duplicate of #7.

**Closed by raiguard** 2023-10-15 16:51 UTC
